name: everem
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.3.5
  fluttertoast: ^8.2.10
  get: ^4.6.6
  lottie: ^3.3.2
  flutter_animate: ^4.5.2
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  uuid: ^4.5.2
  sensors_plus: ^7.0.0
  audioplayers: ^6.5.1
  flutter_ringtone_player: ^4.0.0+4
  file_picker: ^10.3.10
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter_icons:
  android: true
  ios: true
  image_path: "assets/applogo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: helveticaLight
      fonts:
        - asset: assets/fonts/HelveticaNeue-Light.otf  
    - family: helveticaMedium
      fonts:
        - asset: assets/fonts/HelveticaNeue-Medium.otf 

